### ISSUE TITLE
Certified Traceable Digital Thermometer Repair

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#40]
Here is the company information for our probes/meters:
https://www.traceable.com/6412-traceable-platinum-ultra-accurate-digital-thermometer.html

@laurenzane @JillAshey document the issues here along with the catalog numbers of the meters so we can get the 3 meters repaired or get replacement probes

**Comment by AHuffmyer** [comment]
@laurenzane @JillAshey what is the status of this repair?

**Comment by AHuffmyer** [comment]
Also please post the specific issue you are having with each meter (identified by SSN) so we can order the correct parts. Thank you!

**Comment by laurenzane** [comment]
**Digital thermometer and probe pairs:**
(Cat. no. 4000 NIST Traceable® Digital Thermistor Thermometer, -58 Degrees to 302 Degrees F)[https://www.traceable.com/4000-traceable-digital-thermometer.html) => [cat. no. 4111 replacement probe] (https://www.traceable.com/4111.html)
[Cat. no. 6412 Platinum Ultra-Accurate Digital Traceable Thermometer](https://www.traceable.com/6412-traceable-platinum-ultra-accurate-digital-thermometer.html)  => [cat. no 6422] replacement probe (https://www.traceable.com/6422.html

**Issues**
1. Traceable digital thermometer 4000 (serial number not visible) was dropped into seawater at HIMB. Thermometer was taken out and put in rice to dry it out, but it did not fix the thermometer. The probe (4111) port connector is also very rusty and does not appear to be compatible with other thermometers of the same model. 
2. Traceable digital thermometer 6412, SSN: 192676777 needs a new probe. Currently the probe for this thermometer measures temperature when the user is delicately holding the probe at a certain and angle. If the user does not jiggle the probe into place and search around for about the right temperature, the measured temperature can jump rapidly to -100°C to 68°C or other random values.
3. Replacement probe of unknown origin is not compatible with 6412, nor 4000. We could not find this model for sale online.
4. The CBLS upstairs lab shares an Orion meter with the Puritz lab for the titrator. This meter is specifically for use in poisoned water samples. I would like to suggest purchasing an additional Traceable thermometer for the salinity calibration so that the thermometer in the wetlab is not used for this calibration, if possible.

**Comment by JillAshey** [comment]
2 new 4111 probes were received today. 

Hollie cleaned the rice out of the the traceable digital thermometer 4000 (serial number not visible) that was dropped in seawater. It got paired with a new 4111 probe (SSN: 221702482). This set will stay at URI. Labeled as Probe #1. 

A new 4111 probe (SSN: 221720464) was paired with the traceable digital thermometer 4000 (SSN: 2000390599), which had already been working. This set will go to Moorea. Labeled as Probe #2. 

Hollie cleaned rust out of the port of traceable digital thermometer 6412 (SSN: 192676777). It was paired with the 6422 probe (serial number not visible) that was already here. After cleaning, the probe works, but only if held still while using it. Labeled as Probe #3. 

The 2 remaining old probes did not work with Probes 1, 2, or 3. Hollie is seeing if they are compatible with the traceable digital thermometer in the CBLS aquarium room. This thermometer does not need a replacement probe. Labeled thermometer as Probe #4.

**Comment by JillAshey** [comment]
CURRENT PROBE LOCATIONS: 
Probe # 1 = on 3rd shelf of wooden bookshelf next to the door in CBLS 190. 
Probe # 2 = Will be going to Moorea for fall 2022. When it returns, it will go on the 3rd shelf of wooden bookshelf. 
Probe # 3 = in a hard blue case on 1st shelf of wooden bookshelf. 
Probe # 4 = in CBLS aquarium room. 

ThermoFischer thermometer is at the titration station.
