### ISSUE TITLE
Calibrate Pipettes

### ISSUE THREAD

**Issue by zdellaert** [Putnam-Lab/Lab_Management#67]
Next time in-house people come to calibrate pipette, we need to start calibrating our pipettes in cycles.

**Comment by JillAshey** [comment]
@hputnam I talked to Kristina about this and she said the pipette calibrator guy comes 2x a year usually. He typically charges $16/pipette and he will calibrate, fix and grease the pipettes. He will then put a sticker on them that says when they've been calibrated and when they should be calibrated again. It usually only takes a few days. 

She also recommended clearly labeling the pipettes that we want to calibrate so we know how many we gave him and whose lab they came from. She also said it's best to give the pipettes to him in a container so they can all be kept together.

**Comment by hputnam** [comment]
@JillAshey @zdellaert can you please find a company and a quote and start this process of pipette calibration?

**Comment by hputnam** [comment]
@JillAshey @zdellaert can you please find a company and a quote and start this process of pipette calibration by April 20 2024?

**Comment by zdellaert** [comment]
Pipette inventory: 27 total pipettes (23 molecular side, 4 organismal side). All are **Rainin LTS** pipettes.

Molecular Pipettes:
- L-2: 4
- L-20: 5
- L-200: 5
- L-1000: 4
- L-5000: 1
- L-10 Multi-channel: 1
- L-20 Multi-channel: 1
- L-200 Multi-channel: 1
- L-1200 Multi-channel: 1

Organismal Pipettes:
- L-200: 2
- L-1000: 2

**Comment by JillAshey** [comment]
Submitted quote requests to [Transcat](https://www.pipettes.com/calibration-services/service-options) and [VWR](https://us.vwr.com/cms/avantor_services_pipette_calibration_services), waiting to hear back. Also looked at [Rainin](https://www.shoprainin.com/service-selection/pipette-service) and their prices are $51.80 per single channel pipette, $139.00 per 8-channel pipette, and $166.40 per 12 channel pipette.

**Comment by zdellaert** [comment]
Cool! Updated comment above to reflect that we have 3 8-channels and one 12-channel

**Comment by JillAshey** [comment]
[University of Rhode Island Mail in Calibration Quote.pdf](https://github.com/Putnam-Lab/Lab_Management/files/15005278/University.of.Rhode.Island.Mail.in.Calibration.Quote.pdf)

Quote from transcat

**Comment by JillAshey** [comment]
From Transcat reps: "The quote would be the same pricing for 12 channels at this level. You can separate these into as many batches as needed, it is something we typically encourage."

**Comment by hputnam** [comment]
@JillAshey can you check one more place?   I have an account at pipette.com ACCOUNT #70101

https://pipette.com/mm5/pdfs/calibration/Callibration_Orderform_10_4_23_Combined%20Locations.pdf 

https://pipette.com/calibration-get-a-quote-east.html

**Comment by JillAshey** [comment]
Quote requested from pipette.com

**Comment by JillAshey** [comment]
[University of Rhode Island Putnam Lab 4-23-24 (1).pdf](https://github.com/Putnam-Lab/Lab_Management/files/15082393/University.of.Rhode.Island.Putnam.Lab.4-23-24.1.pdf)

Pipette.com calibration quote ($1,157.60), pretty similar to Transcat quote ($1,131.90). @hputnam how would you like to move forward?

**Comment by hputnam** [comment]
@JillAshey I am fine either way. Can you make the decision based on ease of sending things in multiple batches and how long it will take each company to complete the calibration?  I can provide a card payment. Thank you!

**Comment by zdellaert** [comment]
Inventory and calibration info here: https://docs.google.com/spreadsheets/d/1tbLUmAVN0NTHNNC9D9wKw_EKWIH3cUHo7skt_4uGsgM/edit?usp=sharing

Planned to calibrate all pipettes today, 5/10/24, by in-house service if possible. If not, we will calibrate all pipettes 1-27 EXCEPT #s 22,23,26,&27 (a set of 1000,200,20&2).

**Comment by JillAshey** [comment]
Pipettes have been calibrated! They now have a label on them (see below).

![IMG_7077](https://github.com/Putnam-Lab/Lab_Management/assets/63874927/3072c1f3-82e5-4de5-96ec-f180dee790cc)

Zoe and I also numbered them and assigned them a location [here](https://docs.google.com/spreadsheets/d/1tbLUmAVN0NTHNNC9D9wKw_EKWIH3cUHo7skt_4uGsgM/edit#gid=0). PLEASE try to keep them in these locations so that we know where our pipettes are at all times. 

A few things moving forward that the rep recommended to keep our pipettes in good shape: 

- For the multichannel Ranin L-20, he recommended we use the ranin tips for this specific pipette. He showed me that the Biotix tips don't fit as well which is wearing down the part where the pipette and the tip connect. He also said that because the Biotix tips are looser, they yield more variable volumes with this pipette. 

- **IMPORTANT**: He recommended that when we are done using the pipettes for the day, we set them to their max volume (ie 200 uL for the L-200, 1000 uL for the L-1000) in their resting state. He said if we leave the pipettes set at an intermediate volume (ie 100 for the L-200, 500 uL for the L-1000) while they are resting, there is still force being applied to the spring inside the pipette, which will affect how long the calibration is good for. If we set them to their max volume in their resting state, there is no force on the spring so the pipette can "relax".
