### ISSUE TITLE
Clean and test airbrushes that are not spraying water

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#69]
Please clean and test the 2 airbrushes that are spraying air but not water by Feb 2nd.

https://putnamlab.slack.com/archives/CEWKU9WUU/p1705942476396469

https://www.youtube.com/watch?v=WV8XdbpknJk

**Comment by flofields** [comment]
Both are now cleaned, fixed and working.

**Comment by hputnam** [comment]
@flofields can you write a few sentences about what you did from the tips above that made them work again? Thanks!

**Comment by flofields** [comment]
Yes. I'm adding it to the Lab Equipment repair sheet you sent in slack today.

**Comment by hputnam** [comment]
@flofields the details of how the repair was completed go here so that after the issue is closed we can still find the answer if it happens again in the future. Thanks!

**Comment by flofields** [comment]
In fixing this issue the first step was to establish possible determinants that caused the problem using the company's [troubleshooting page](https://www.iwata-airbrush.com/blog/troubleshooting/) and google which led me to this [website](https://www.everythingairbrush.com/airbrush-troubleshooting-guide/#:~:text=This%20can%20be%20caused%20by%20many%20things%3B%20the,%E2%80%93%20Check%20and%20tighten%20the%20needle%20chucking%2Flocking%20nut.). 
Note that they were two problematic iwata airbrushes, both with model number Eclipse HP-BCS that were not spraying any water.
First iwata airbrush: After assessing the issue, the possible determinant was a clogged/blocked nozzle which required unblocking via a thumbtack or cleaning with a cleaning kit. 
Note: We did not have a cleaning kit
I disassembled the entire airbrush using [this video](https://www.youtube.com/watch?v=8WaZx_AG7EI). then cleaned the inside with the use of a Q-tip and a little DI water to remove any dirt. I also used this method to clean the vents/nozzle connections because the thumb tack was too short. I then used the BSC fluid needle to check that the bottom feeding vent was not clogged. The state of being unclogged was determined on whether or not the needle could be seen through the hole on the front of the body of the airbrush after being disassembled. The iwata lube was then lightly used on the needle with the q-tip and a drop was added to the packing head O-ring and the Needle chucking nut. Using the video used to disassemble was used to reassemble the airbrush, it was then connected to the compressor to testing with the use of a zip lock bag with dry tissue to determine if the airbrush was spraying an adequate amount of water. The airbrushed worked.
Second iwata airbrush: The steps used for the first airbrush were repeated twice but did not work. The airbrush was then tested for a third time to determine any problems that were missed. The BCS needle was then noticed to not retract when the trigger is pulled back. This led to the conclusion that the issue was with the locking nut, the needle itself or the trigger. The trigger was checked first, to do this the Needle Cap, Nozzle Cap, Head cap and the Pre-set handle were removed from the airbrush to confirm that the needle was not moving although the trigger was moving back. 
Note: The Needle chucking nut not only affects the needle's ability to move but the trigger's ability to retract.
The next step was to remove the needle and put it back. I then realized the needle moving in the Nozzle E5 was a little stiff so the Nozzle E5 was recleaned with a q-tip and DI water then lube was added using a q-tip. The airbrush was then reassembled. The needle chucking nut was adjusted a few times ensuring the trigger was still working until I eventually saw the needle retract. The airbrush was then tested using a zip lock bag with dry tissue inside.
After these steps the second airbrush is now working, and both can be found in draw BD7.
For a list of airbrush parts/location see [HERE.](https://www.dixieart.com/Iwata_Eclipse_Parts_and_Schematic.html)
