### ISSUE TITLE
HI 2024 SAP Report

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#79]
Prepare and submit 2024 Putnam Barott SAP Report 

[SAP 2024-24 Hollie Putnam-University of Rhode Island-HIMB-Coral-Kaneohe Bay APPROVED_signed.pdf](https://github.com/Putnam-Lab/Lab_Management/files/15078165/SAP.2024-24.Hollie.Putnam-University.of.Rhode.Island-HIMB-Coral-Kaneohe.Bay.APPROVED_signed.pdf)

**Comment by AHuffmyer** [comment]
Emailed all collaborators with submission information; waiting for responses

**Comment by AHuffmyer** [comment]
Please do the following: 

1) [Fill out the report spreadsheet here](https://docs.google.com/spreadsheets/d/1QE83dknF8DZ0AjHIg7OKa6q_3uWZ2QHB_Dzsr74UFsE/edit#gid=0). This spreadsheet has instructions in the header of each column and drop down menus as required by DLNR for formatting our report. Please enter a separate line for each unique entry. For example, I entered a unique line for each set of samples collected from each site split by current storage location and disposition. Enter any descriptions or information as necessary in the notes column. Let me know if you have any questions. Please refer back to the original permit to confirm that your collections were within the original permit requests and cite the correct species and site codes. [You can view the permit here](https://drive.google.com/file/d/1QtxiOuHJ-8Ufk9VzsQr4luEXf8OpocAJ/view?usp=sharing). 

2) [Fill out the report narrative here](https://docs.google.com/document/d/1_Oc1IsGzR0I_aDp6JXfYczkiAkekksVQf5DbRb9mXDA/edit). This document contains a template for reporting and describing activities during the reporting period. Please enter your project information, photos of the collections/project, and a description of any results or project status if available. Please also include any publications from this or previous Hawaii SAP permits. You'll see my entry first and you can scroll down to find empty templates to enter your descriptions. Add any headings as necessary. 

3) Please comment here or email Ariana once you have completed the entries so that we know it is complete.

**Comment by AHuffmyer** [comment]
@JillAshey @hputnam

**Comment by JillAshey** [comment]
Completed report narrative and spreadsheet. Let me know if anything else is needed from me!

**Comment by AHuffmyer** [comment]
Report complete, uploaded here for @zdellaert to submit with new request: https://drive.google.com/drive/u/2/folders/1MKG3mwKR9jpOymds7IpVbPljO4iHTj2x
